# Generated by Django 2.0.1 on 2018-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Please enter Title of Post', max_length=200, verbose_name='post title')),
                ('body', models.TextField(blank=True, help_text='Please enter Body of Post', null=True, verbose_name='post body')),
                ('slug', models.SlugField(allow_unicode=True, max_length=40, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='post image')),
                ('local_view_count', models.IntegerField()),
                ('global_view_count', models.IntegerField()),
            ],
        ),
    ]
