# Generated by Django 2.1.4 on 2018-12-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgurl',
            name='img_style',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
