# Generated by Django 2.0.4 on 2018-06-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='event_kind',
            field=models.CharField(blank=True, choices=[('t', 'Tests Week'), ('m', 'Mid Term Examinations'), ('f', 'Final Examinations'), ('s', 'Seminar'), ('w', 'Workshop'), ('h', 'Holiday'), ('m', 'Make-Up Class'), ('n', 'Notice')], default='n', help_text='Notice Type', max_length=1),
        ),
    ]
