# Generated by Django 2.0.4 on 2018-08-15 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], default='S', max_length=1)),
                ('discount', models.FloatField()),
                ('promotion', models.FloatField()),
                ('promotion_available', models.BooleanField(default=False)),
                ('preperation_time', models.DurationField(default=datetime.timedelta(0, 1800))),
                ('servings', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('qoute', models.TextField()),
                ('calories', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('item_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.Item')),
                ('drinks_ordered', models.CharField(choices=[('D', 'Mountain New'), ('C', 'Coca Cola'), ('W', 'Mineral Water')], default=None, max_length=1)),
            ],
            bases=('restaurant.item',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurant.Item')),
                ('inch', models.FloatField()),
                ('topping', models.CharField(choices=[('C', 'Cheeze'), ('S', 'Sausages'), ('P', 'Prawns')], default=None, max_length=1)),
                ('crust', models.TextField()),
                ('ingredients', models.TextField()),
            ],
            bases=('restaurant.item',),
        ),
    ]
