# Generated by Django 2.0.4 on 2018-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(help_text='Enter a title for the notice (e.g. Make-Up Class.)', max_length=200)),
                ('notice_text', models.TextField(help_text='Enter a description for the notice.')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Published on')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Takes place on')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
