# Generated by Django 2.0.4 on 2018-06-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0003_notice_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='posted_by',
        ),
    ]
