# Generated by Django 2.0.4 on 2018-06-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('message_board', '0004_remove_notice_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group'),
        ),
    ]
