# Generated by Django 3.1.5 on 2021-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210109_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edited_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date Commented'),
        ),
    ]
